export const countries = [
    {name:"World",code:""},
    { name: 'East Timor', code: 'TP' },
    { name: 'Samoa', code: 'WS' },
    { name: 'Japan', code: 'JP' },
    { name: 'French Southern Territories', code: 'TF' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'North Korea', code: 'KP' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'Malta', code: 'MT' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Taiwan', code: 'TW' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Eastern Asia', code: 'UN030' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Yugoslavia', code: 'YU' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Congo - Kinshasa', code: 'CD' },
    { name: 'Micronesia', code: 'UN057' },
    { name: 'Andorra', code: 'AD' },
    { name: 'Union of Soviet Socialist Republics', code: 'SU' },
    { name: 'Rwanda', code: 'RW' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Norway', code: 'NO' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Somalia', code: 'SO' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Falkland Islands', code: 'FK' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Middle Africa', code: 'UN017' },
    { name: 'Central Asia', code: 'UN143' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'Southern Europe', code: 'UN039' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Belgium', code: 'BE' },
    { name: 'World', code: 'UN001' },
    { name: 'Congo - Brazzaville', code: 'CG' },
    { name: 'Southern Asia', code: 'UN034' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Aland Islands', code: 'AX' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Central America', code: 'UN013' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Moldova', code: 'MD' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Chad', code: 'TD' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Western Europe', code: 'UN155' },
    { name: 'Mali', code: 'ML' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Albania', code: 'AL' },
    { name: 'Angola', code: 'AO' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Serbia and Montenegro', code: 'CS' },
    { name: 'Northern America', code: 'UN021' },
    { name: 'Palestinian Territory', code: 'PS' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Greece', code: 'GR' },
    { name: 'Zaire', code: 'ZR' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Southern Africa', code: 'UN018' },
    { name: 'Canada', code: 'CA' },
    { name: 'Afghanistan', code: 'AF' }
];